### ISSUE TITLE
Forms should be exact replicas of GON DTCs

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#10]
Ensure all forms are GON DTCs compliant

**Comment by MrOluGbenga** [comment]
Client Intake Form- Status : Good
Client Referral form- Status: Good
Pharmacy Order Form - Status: Good
Client Tracking and Termination Form - Status: Good

**Comment by MrOluGbenga** [comment]
**Transfer Form - Good**
**Adult Initial Clinical Evaluation Form - Incomplete**

_Symptom review 

Genital discharge
Genital itching
New visual imparity
Pain/difficulty when swallowing					
Pain (other site)
Oral Sores (Repeated)

Physical exam - (Respiratory)

Auscultation findings (Repeated)
Rate   _________ breaths/min		

Physical exam -(Cardiovascular)
Auscultation finding

32a. Regimen
32 b. Drugs in regimen
33. Next appointment_	

**Laboratory Order & Result Form - Incomplete**

_Drug Regimen
Results
Additional tests (only be performed by laboratory if exact clinical indication specified and signed by clinician!)																	
Specify exact clinical indication for requested tests_

**Comment by elameen221** [comment]
Pediatric Initial Clinical Evaluation
**Cardiovascular**: There is no field to specify findings as opposed to the GON form.
Missing out **ART Regimen Field** (Drop down List)

**Comment by MrOluGbenga** [comment]
National PMTCT HTS Register - Good
Partner Register - Good

**Comment by elameen221** [comment]
**HIV Enrollment Form and Care Card 1 form are similar**
Under Enrollment Details
   - Baseline Screening - Missing
   - Opportunistic Infections - Missing
   - ART Initiation not exactly the same - Missing

**General Antenatal Care Form : Complete**
**Maternal Follow  up Form** (To be reviewed whether to be discarded or not) 
  - All fields are complete (but some are not working as they should)

**Comment by ahmedsylvanus** [comment]
Can we have the list of your comparison with their status itemized in an excel sheet. It will be better to track missing fields to be added to identified forms.

**Comment by elameen221** [comment]
**Pediatric Initial Clinical Evaluation** - Complete
The **Other** check box now opens an additional text field to specify findings.
ART Regimen Field (Drop down List) has been added

**Comment by MrOluGbenga** [comment]
PLHIV Presumptive TB Screening and INH Preventive Therapy (IPT) Monitoring - Good

Child Birth Information - Incomplete
DOB, Age, Infant's Name, Sex are all missing on the electronic form

**Comment by elameen221** [comment]
**PMTCT Delivery Register** - Complete

**Comment by elameen221** [comment]
**HIV Treatment Follow up form (Care Card - Center Spread) : Incomplete**
***Missing Fields***
Under **ARV Drugs**
 - Regimen - missing

Under **COTRIMOXAZOLE**
 - Dose - missing

Under **INH**
 - Dose missing

Other Drugs Prescibed - missing
CD4 - missing
Viral Load - missing
Other Tests Done - missing
Consult Hospitalise Refer Link -missing

**Comment by elameen221** [comment]
**Update** 

1. **Child Birth Information Form** was newly introduced, originally there was no _Child Birth Information GON form_, so this form is complete.

2. **HIV Treatment Follow up form (Care Card - Center Spread)** - The  missing fields on this form exist on the Laboratory Order and Result Form, so  there is no need including them in here.

3. **HIV Enrollment Form** - The missing fields on this form have been captured at the initial clinical evaluation and laboratory order forms. Pregnancy  and breastfeeding status fields were included to the  form.

4. **Laboratory Order & Result Form** - The missing fields already exist in the pharmacy order form, there is no need repeating them here.

5. **Adult Initial Clinical Evaluation Form** - The missing fields were included and the repeated fields were removed.

With this all NMRS forms compared against the GON Forms are now complete.
