### ISSUE TITLE
ART forms now showing  

### ISSUE THREAD

**Issue by wonderfulguru1** [nmrs-nigeria/openmrs-module-nigeriaemr#100]
After updating with new database the ART forms are not showing  even when you enroll patients into the HIV Program. User have to fill form via the legacy interface @multiplechuks kindly look into this

**Comment by multiplechuks** [comment]
@wonderfulguru1 can you confirm from the database you have, has the encounterType for `ART (antiretroviral therapy) Programs` as `11eb2647-91b4-482a-9cb3-08573e0d219b`.

Regards

**Comment by wonderfulguru1** [comment]
> @wonderfulguru1 can you confirm from the database you have, has the encounterType for `ART (antiretroviral therapy) Programs` as `11eb2647-91b4-482a-9cb3-08573e0d219b`.
> 
> Regards
@multiplechuks  the DB contains 11eb2647-91b4-482a-9cb3-08573e0d219b instead for that encounter type HIV Enrollment

**Comment by multiplechuks** [comment]
@wonderfulguru1 I have assigned this to you, plese letme know the outcome

**Comment by wonderfulguru1** [comment]
Updated the coreapp module from the git repo and it came up
