### ISSUE TITLE
Missing Second Line Regimen

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#105]
TDF-DTG-LPV/r   regimen combination not found on NMRS

**Comment by brightoibe** [comment]
A concept need to be created for this regimen

**Comment by ahmedsylvanus** [comment]
Can we have a list of Regimens they will require to see, so we don't keep going back and forth with this. Also provide all possible drug combinations for the regimens. This regimen was not included in the Harmonized regimen shared earlier

**Comment by brightoibe** [comment]
Spoke with some Pharmacist and a Doctor the said the Regimen is not valid combination.
