### ISSUE TITLE
Next appointment date has to be later than visit date on CareCard

### ISSUE THREAD

**Issue by abrahamolatubosun1973** [nmrs-nigeria/openmrs-module-nigeriaemr#115]
Hello house,

We are currently having issue with updating back-log on care card, during update you supply visit date (12/10/2019) and next appointment (15/12/2019) on clicking submit you get the following error **"Next appointment date has to be later than visit date"**.

From the HTML Editor, i have set allowFutureDates to True. Yet the issue is still there.

Kindly advice on the way forward.

Thanks

**Comment by talk2morris** [comment]
Hello Abraham I just confirm the issue you raised. This was as a result of a hidden field in the html file that also points to encounterDate.
But this has been fixed. kindly download the fixed care card form here:

https://github.com/nmrs-nigeria/files_and_resources/commit/b720b5543eefa7bc44e5641c8c10954ade422d47
