### ISSUE TITLE
Issue with empty tags for patient EducationalLevelCode when exporting from NMRS

### ISSUE THREAD

**Issue by talk2morris** [nmrs-nigeria/openmrs-module-nigeriaemr#117]
Due to feedback from IPs we noticed that the NMRS-NDR tool exports empty tags for unknown patient educationLevelCode.

**Comment by talk2morris** [comment]
This has been fix and the omod file has been updated too.

**Comment by abrahamolatubosun1973** [comment]
Great work Chief Morris, we will surely download the omod and share
