### ISSUE TITLE
Reporting_NDR_Missing HIVCommonQuestions attributes

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#13]
Key attributes like DateDiagnosed, DateOfFirstReport,DateOfLastReport,PregnancyState, EDD do not show up on the HIVCommonQuestion element

**Comment by wonderfulguru1** [comment]
Key attributes now showing as required. I corrected the concept ID in the concept mapping dictionary
and set the appropriate nodes
