### ISSUE TITLE
XSD File Not Well Formed.

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#132]
Online XSD validation tool kept saying that the XSD file below

https://github.com/nmrs-nigeria/files_and_resources/blob/master/Release/nigeriaemr/1.6.0/NDR%201.6.xsd

is not well formed. Until I changed the header from `<?xml version="1.0" encoding="utf-8" ?>` to `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>`
Please help verify that the XSD is well formed @wandechris @talk2morris @wonderfulguru1 .

**Comment by wandechris** [comment]
@brightoibe some text is omitted from your post

**Comment by wandechris** [comment]
@brightoibe different online validators use a different format for validations, if the XML sent to NDR is fine, then it's well-formed.

also, the XSD comes from NDR.
