### ISSUE TITLE
Warning Messages for LGA and State at NDR Validation Level

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#134]
Hello @wandechris @caniekwe @talk2morris @wonderfulguru1 . I noticed that thousands of patients in my database are failing this validation
'<xs:element name="StateCode" type="CodeType" minOccurs="1" maxOccurs="1">'
'<xs:element name="LGACode" type="CodeType" minOccurs="1" maxOccurs="1">'
and many of these patients are LTFU, some Transferred Out, Also some Active patients because of Stigma will not give you any hint of their address and phone numbers.  I recommed we implement a warning validation flag for this at NDR upload level so that the DAs can clean up the data over time, rather than at XSD level. This is to allow the clean up of these data elements especially for Active patients to happen over time and not disrrupt reporting.

**Comment by wandechris** [comment]
the validations are because they are missing in the XML, it doesn't stop the file generation process

**Comment by caniekwe** [comment]
@brightoibe may I suggest you begin working with your DAs to clean up the data beginning with the active patients

**Comment by wandechris** [comment]
@brightoibe can i close this issue or do you have any other concern
