### ISSUE TITLE
Challenges with the assignment of future dates (Next Appointment)

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#14]

**Comment by caniekwe** [comment]
@MrOluGbenga  Can u put some description to this issue.

**Comment by caniekwe** [comment]
@elameen221 Can you go through all the forms and confirm that this has been resolved. The forms to look out for:
- Adult Initial Clinical Evaluation form
- Pediatric Initial Clinical Evaluation form
- Care Card

**Comment by elameen221** [comment]
These forms have been checked and the issue with the  **HIV Treatment Follow up form (Care Card - Center Spread)** has been resolved by setting allowFutureDates="true" `<obs conceptId="5096" id="next_appointment" allowFutureDates="true"/>`
