### ISSUE TITLE
Wrong Mapping in Pregnancy Status in ClinicalDictionary

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#149]
There is a wrong mapping on the Pregnancy/Breastfeeding Status on the ClinicalDictionary.java class line 246, 247 and 248.

165048 (Pregnant) ---- P
165049 (Breastfeeding) ----NP (Instead of BF)
165047 (Not Pregnant) ---- BF

This is supposed to be mapped like this

165048 (Pregnant) ---- P
165049 (Breastfeeding) ----BF
165047 (Not Pregnant) ---- NP

@wandechris , @talk2morris , @caniekwe , @henryvalentine @ahmedsylvanus 

Please this needs urgent fixing

**Comment by brightoibe** [comment]
Also put a comment on Pregnancy on that section just like the other ones so it can be easy to locate

**Comment by wandechris** [comment]
@wonderfulguru1 this can be closed out
