### ISSUE TITLE
Key data quality restrictions/validations not available

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#15]

**Comment by dkayiwa** [comment]
Is this in any way related to https://wiki.openmrs.org/display/docs/Validation+Module
Or this? https://wiki.openmrs.org/display/docs/Data+Integrity+Module

**Comment by caniekwe** [comment]
Some requirements should be:
- Validate all date formats
- Range limits for selected data variables
   - Date started on ART should not be before date found eligible for ART
   - Date enrolled in care cannot be before date of birth
   - Vital signs shall be validated against normal human ranges, including:
      - Weight
      - Height
      - Blood pressure
      - BMI
- The system should not allow for selection of pregnancy or female-related questions when the client is male.
- Required data elements are made mandatory (cross-check with the data/concept dictionary)
