### ISSUE TITLE
Manual "Start Visit" Activation before form Load

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#16]

**Comment by meks285** [comment]
**Insight**: It has been reported that facility data entry staff often commence the filling of forms without having to click the "Start Visit" button which results in the form data not being visible/accessible on the NMRS EMR.

One of the three options below can be chosen as the best option to remedy this situation moving forward.

1. Moving all Form Entry links from the Patient Landing Page, leaving only the "Start Visit" and "Add Past Visit" Links. The Data Entry Forms become visible once the "Start Visit"/"Add Past Visit" links have been clicked and confirmed. **_If this becomes the approved option then the responsibility for implementation moves to the Workflow Team._**

2. Remove the "Start Visit" and "Add Past Visit" links, create a class that automatically starts a Visit once the necessary forms links are clicked.

3. Each IP to sensitize by means of training their Data Entry staff on the Importance of the "Start Visit" and "Add Past Visit" options.

Option 1 Eliminates the need for committing extra resources to sensitization & creating of Classes via coding.

**Comment by dkayiwa** [comment]
If option 2 is chosen, you would use this: https://wiki.openmrs.org/display/docs/HTML+Form+Entry+Module+HTML+Reference#HTMLFormEntryModuleHTMLReference-%3CpostSubmissionAction%3E

Examples can be seen here: https://github.com/search?l=&q=org%3Aopenmrs+CustomFormSubmissionAction&ref=advsearch&type=Code

**Comment by meks285** [comment]
Thank You Daniel for the resource, We will be reviewing all options.

**Comment by dkayiwa** [comment]
@meks285 did anyone create an issue for preventing certain forms from being filled before others?

**Comment by meks285** [comment]
Not Yet.

**Comment by meks285** [comment]
@dkayiwa Not Yet.

**Comment by caniekwe** [comment]
Yes this was logged and is being handled by the workflow team. [https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/issues/6](url)

**Comment by dkayiwa** [comment]
How about simply displaying forms only when there is an active visit? That is by using something like: "show If =  visit & visit.active" as documented here: https://wiki.openmrs.org/display/docs/Conditionally+displaying+Apps+and+Extensions

**Comment by gibrilg** [comment]
The scope of this has changed this morning right after the delibrations, its currently being reviewed and will present the update soon.

**Comment by meks285** [comment]
This is noted.

**Comment by ahmedsylvanus** [comment]
The fix for this issue already exists in OpenMRS

1. Click on Administration
2. Click configure visit
3. Click the check boxes 'Enable visit' and 'start auto close visits task'
4. Select 'facility' in the 'Visit types to auto close' option
5. Save configuration
Visit will be auto started upon form submission and will be auto closed in 24 hours
