### ISSUE TITLE
Reporting_NDR State and LGA coding

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#20]
State and LGA should follow standard NDR coding

**Comment by dkayiwa** [comment]
The available address hierarchy service methods can be found at: https://github.com/openmrs/openmrs-module-addresshierarchy/blob/master/api/src/main/java/org/openmrs/module/addresshierarchy/service/AddressHierarchyService.java

**Comment by emadubuko** [comment]
The NDR coded value for each state and LGA has been inserted into the user_generated_id column of the address_hierarchy_entry table. The ndr export module will query this table using the values from the patient_address. 

Download this attached zip and run the file to create the address_hierarchy_table with the correct NDR coded value


[address hierarchy table.zip](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3566503/address.hierarchy.table.zip)
