### ISSUE TITLE
PrescribedRegimenTypeCode "OI" not recognized. This should be changed to NONART

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#213]
All OIs exported on the XML inside the "Regimen" tag with PrescribedRegimenTypeCode of OI is being flagged by the NDR plugin.

**Comment by brightoibe** [comment]
`   try {
                //set type code
                if (obs != null && obs.getObsGroup().getConcept().getConceptId() == OI_regimen_Concept_set) {
                    regimenType.setPrescribedRegimenTypeCode("OI");
                } else if (obs != null && obs.getObsGroup().getConcept().getConceptId() == TB_regimen_Concept_set) {
                    regimenType.setPrescribedRegimenTypeCode("TB");
                }
            } catch (Exception ex) {
                LoggerUtils.write(PharmacyDictionary.class.getName(), "Error on OI_regimen_Concept_set: " + ex.getMessage(), LogFormat.FATAL, LogLevel.live);
            }   `

I think this can be fixed from line 461 t0 470 of PharmacyDictionary.java class 
( 
https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/blob/master/omod/src/main/java/org/openmrs/module/nigeriaemr/ndrfactory/PharmacyDictionary.java
 )

**Comment by wandechris** [comment]
Hi @brightoibe  what version of export plugin was this, please provide the sample file that failed?

**Comment by brightoibe** [comment]
[33550_Ke1y8vsmeC4_RIV20700500_260121.zip](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/6154596/33550_Ke1y8vsmeC4_RIV20700500_260121.zip)

**Comment by wandechris** [comment]
@wonderfulguru1  please take a look at this

**Comment by brightoibe** [comment]
This is the beta version of 1.6.3

**Comment by wonderfulguru1** [comment]
@brightoibe I just validate the file with XSD 1.6.3 and it went through I discover one regimen encounter didn't have prescribed regimen tag so it got flagged

**Comment by brightoibe** [comment]
Please can you validate against XSD 1.6.2 because that is the current XSD used by the plugin version 1.6.2
