### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by teggsdgreat** [nmrs-nigeria/openmrs-module-nigeriaemr#22]
1.	Create a Concept Mapping template - current to latest.
2.	Generation of matching dataset from Respective IP EMRs
3.	Develop a unified Data submission tool into NMRS – utility to be developed
         a.  Demographic Information
         b.  Treatment information
                       i.	ART Start Date
                       ii.	Regimen
         c.   Viral Load information
         d.  Additional information
4.	Validation of IP specific data extraction -  using the OpenMRS API
5.	Testing and validation of migrated data - Performance testing
6.	Create a Documentation for data migration into NMRS
7.	Ensure a system for updating the concept Dictionary after the boot camp is in place

**Comment by JohnboscoJbTech** [comment]
This was closed because it has to be splitted
