### ISSUE TITLE
Sample ID data type is numeric instead of text.

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#23]
Numeric value in Sample ID should be changed to text.

**Comment by meks285** [comment]
This has been Fixed using the following steps:
1.) Login to the OpenMRS portal as SuperUser
2.) Navigate to System Administration -> Advanced Administration -> Dictionary 
3.) Search for concept ID 165028
4.) Click to Open -> Edit
5.) Change DataType from text to Numeric, Check the "Allow Decimal" button.
6.) Click "Save and Continue"/"Save Concept"

Image Below:
![image](https://user-images.githubusercontent.com/38112486/63384905-c25f1500-c397-11e9-882d-1536cac6f420.png)

Note: **_This will become necessary to Implement after the decision to add the Dosage field to the pharmacy order form has been confirmed._**

**Comment by meks285** [comment]
165028 - Medication Dose (Concept)

**Comment by MrOluGbenga** [comment]
Issue resolved by @meks285
