### ISSUE TITLE
HTML Form Submission via the Java API

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#24]

**Comment by talk2morris** [comment]
I have gotten a clue from Daniel to use obs for this

**Comment by caniekwe** [comment]
@talk2morris can you put a description of what this issue was and what resolution was taken on this.

**Comment by talk2morris** [comment]
The request talks about a clean way of posting to htmlforms via the Java API, I mean an API that maybe takes the formID and the concept and values as a map, if this was available one could neatly integrate this into a data migration utility from other EMR to NigeraMRS. This is a feature I would love to see in future versions of openmrs.
