### ISSUE TITLE
Develop a unified Data submission tool into NMRS – utility to be developed

### ISSUE THREAD

**Issue by JohnboscoJbTech** [nmrs-nigeria/openmrs-module-nigeriaemr#27]
This is a tool that will assist in migrating the generated data from NATIVE EMRs through OPENMRS form API to NMRS. This needs to follow a specific pattern
a. Demographic Information
b. Treatment information
    &nbsp;&nbsp; i.	ART Start Date
    &nbsp;&nbsp;  ii.	Regimen
c. Viral Load information
d. Additional information

**Comment by ahmedsylvanus** [comment]
The Migration utility has been implemented.
