### ISSUE TITLE
Nigeria MRS workflow - Inability to Sort forms based on patient program

### ISSUE THREAD

**Issue by caniekwe** [nmrs-nigeria/openmrs-module-nigeriaemr#3]
Forms needs to be displayed based on the program a patient is enrolled in.

**Comment by dkayiwa** [comment]
Can you put here a link to the OpenMRS Talk thread where this was asked?

**Comment by arinzeeze** [comment]
https://talk.openmrs.org/t/display-forms-for-patients-based-on-the-program-s-enrolled/17568

**Comment by dkayiwa** [comment]
@arinzeeze can you update that openmrs talk thread with a link to the ticket that you created?

**Comment by dkayiwa** [comment]
@caniekwe or @arinzeeze or any one else, i have curated this ticket to such an extent that it should be simple to take on and fix by any of you guys: https://issues.openmrs.org/browse/RA-1619

**Comment by arinzeeze** [comment]
https://issues.openmrs.org/browse/RA-1620

**Comment by nsanmi** [comment]
@arinzeeze and @caniekwe .
I think this NMRS section is completed.
UI conditions has been implemented based on @arinzeeze modification to the new coreapp module.
All forms has been conditioned according to programs area and data entry clerks can now access required forms for specific program areas.

**Comment by dkayiwa** [comment]
This cannot be considered done because there is no commit any where. So we do not know where the changes for this new feature, are.

**Comment by dkayiwa** [comment]
I would not recommend closing this because the code is not committed any where that am aware of. 😊

**Comment by ahmedsylvanus** [comment]
This has been done and the code committed to the Dev instance

**Comment by dkayiwa** [comment]
@ahmedsylvanus am reopening this until when some one posts here a link to the commit.

@arinzeeze did you commit this anywhere that am not yet aware of?

**Comment by caniekwe** [comment]
@arinzeeze was the modification commited? Can you put the link to the commit here for future reference
