### ISSUE TITLE
Ensure a system for updating the concept Dictionary after the boot camp is in place

### ISSUE THREAD

**Issue by JohnboscoJbTech** [nmrs-nigeria/openmrs-module-nigeriaemr#30]
This is going to state the after plan of who manages and distributes newly created concept and how the whole process is to be managed

**Comment by ahmedsylvanus** [comment]
Going forward, creation of new concepts will be channeled via UMB. We will create requested concept and update the Concept dictionary, thus maintaining a Harmonized concept dictionary across all partners.
