### ISSUE TITLE
Concept mapping PMTCT HTS Register

### ISSUE THREAD

**Issue by lisamurie** [nmrs-nigeria/openmrs-module-nigeriaemr#32]

**Comment by lisamurie** [comment]
NMRS form concepts to global CIEL Dictionary concepts

**Comment by abrahamolatubosun1973** [comment]
HTS PMTCT Register : The form elements have been pull into the template for further matching with Global CIEL  dictionary, possibly completion today

**Comment by abrahamolatubosun1973** [comment]
In addition to the HTS PMTCT Register, the following forms have also conclude mapping  Pharmacy Order Form, Transfer Form, Vitals. We are yet to compare with the Global CEIL
