### ISSUE TITLE
Patient Dashboard - Display Patient Identifier of interest on the Patient Dashboard (Header)

### ISSUE THREAD

**Issue by caniekwe** [nmrs-nigeria/openmrs-module-nigeriaemr#5]
Using the UI framework, the identifier displayed on the patient dashboard is openmrs ID, IDs to display should be dependent on the Patient Programs

**Comment by gibrilg** [comment]
Currently, the fix only shows PEPFAR ID as the predefine ID at the header section of the patient clinical facing page

**Comment by gibrilg** [comment]
Currently, the fix only shows PEPFAR ID as the predefine ID at the header section of the patient clinical facing page. But I think this can be improved on to program-specific.
