### ISSUE TITLE
Generate dataset from legacy EMR based on updated NMRS Data Dictionary  -  CCFN

### ISSUE THREAD

**Issue by lisamurie** [nmrs-nigeria/openmrs-module-nigeriaemr#53]

**Comment by teggsdgreat** [comment]
(1) Resolved an issue of migrated provider not showing as a select option in various forms. To do this we ensured provider information is present in the following tables;
openmrs.person;
openmrs.person_name;
openmrs.users;
openmrs.user_role;
openmrs.providermanagement_provider_role;
openmrs.provider;

(2) Mapping NMRS concept IDs to CCFN native EMR is still ongoing

**Comment by lisamurie** [comment]
@teggsdgreat thanks. Can we move this comment  (1) to the discussion page on the Data Migration  Team page?

**Comment by lisamurie** [comment]
@teggsdgreat also create an issue describing issue (1) and comment how resolved it before closing it. Please tag me -  thanks.

**Comment by teggsdgreat** [comment]
Data set for CCFN EMRs have been generated and test carried out to check validity of the generated data set. This is okay and done.

**Comment by lisamurie** [comment]
thanks Teggs
