### ISSUE TITLE
Generate dataset from legacy EMR based on updated NMRS Data Dictionary  -  APIN

### ISSUE THREAD

**Issue by lisamurie** [nmrs-nigeria/openmrs-module-nigeriaemr#56]

**Comment by michaelnnakwe** [comment]
Forms Completed so far
1. Laboratory form
2. Pediatric Initial Clinical Evaluation
3. Adult Initial Clinical Evaluation
4. Pharmacy form

**Comment by michaelnnakwe** [comment]
Please find attached completed mapping file for APIN

[APIN_dataset_legacy_EMR_on_updated_NMRS_Data_Dictionary.xlsx](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3563631/APIN_dataset_legacy_EMR_on_updated_NMRS_Data_Dictionary.xlsx)
