### ISSUE TITLE
NigeriaMRS workflow- Preferred Identifier should be displayed on the UI Framework manage patient

### ISSUE THREAD

**Issue by arinzeeze** [nmrs-nigeria/openmrs-module-nigeriaemr#57]

**Comment by caniekwe** [comment]
@arinzeeze  Can you put a description to this issue

**Comment by arinzeeze** [comment]
![dashboard](https://user-images.githubusercontent.com/54318558/63577140-aae57f00-c585-11e9-9a33-029416907825.PNG)

**Comment by arinzeeze** [comment]
The identifier should be the patients' hospital number and not openmrs ID

**Comment by caniekwe** [comment]
Melody seems to have found a solution for this.

**Comment by dkayiwa** [comment]
@caniekwe what is Melody's github id?

**Comment by enumahin** [comment]
enumahin@gmail.com

**Comment by dkayiwa** [comment]
@enumahin do you mind sharing your solution here?

**Comment by enumahin** [comment]
@dkayiwa I actually discovered that it's the preferred Identifier that appears there, so @henryvalentine is working on displaying multiple identifiers at patient registration level the problem will be solved permanently from there.

I am also looking into displaying multiple identifiers on the patient search page. like OpenMRS ID, Preferred Identifier and Hospital Number.

**Comment by ahmedsylvanus** [comment]
@henryvalentine Please comment on your fix for this.
