### ISSUE TITLE
Customization of the Nigeria OpenMRS EMR

### ISSUE THREAD

**Issue by mustybello** [nmrs-nigeria/openmrs-module-nigeriaemr#58]
Could we also begin to work through NMRS application/homepage customization?

**Comment by gibrilg** [comment]
This is quite possible, I can replicate this to the live server. Are we going with the Nigeria coat of arm?

**Comment by gibrilg** [comment]
This is completed, the Nigeria coat of arm is added alongside the NigeriaMRS distribution name.

**Comment by mustybello** [comment]
Great work, Gibril.
