### ISSUE TITLE
Data Entry Missing LMP and EDD on the Adult Initial Clinical Evaluation Forms

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#59]
Pregnancy status, EDD and LMP is missing on the Adult Initial Clinical Evaluation Forms. Should be added

**Comment by MrOluGbenga** [comment]
The LMP and EDD are not missing, you just have to select a female patient for the row to display. The row is hidden by default when you select a male patient.
