### ISSUE TITLE
NigeriaMRS workflow - Ensure that form filling follows the correct order

### ISSUE THREAD

**Issue by arinzeeze** [nmrs-nigeria/openmrs-module-nigeriaemr#6]

**Comment by dkayiwa** [comment]
Is this similar to? https://talk.openmrs.org/t/how-to-conditionally-display-forms/4197/10

**Comment by caniekwe** [comment]
Yes it is, I have done a follow on to the post, lets see if their is a feedback

**Comment by dkayiwa** [comment]
Documentation for the Show If functionality can be found at: https://wiki.openmrs.org/display/docs/Conditionally+displaying+Apps+and+Extensions

**Comment by dkayiwa** [comment]
@caniekwe can you look at the response which has just been given on the above talk thread and see if it helps you to move on?

**Comment by caniekwe** [comment]
@nsanmi  Can we look at this in addition to what you are doing [https://talk.openmrs.org/t/how-to-conditionally-display-forms/4197/30 ](url)

**Comment by caniekwe** [comment]
> @caniekwe can you look at the response which has just been given on the above talk thread and see if it helps you to move on?

Yes I have. We will be trying that and the Show If functionality. whichever works for us

**Comment by nsanmi** [comment]
I was able to implement a conditional check with formEncounterType and formuuid, where the page is to redirect the user to the dashboard if the encountertype for the form has not been filled.

I and the workflow team will together look at the solution provided tomorrow

**Comment by dkayiwa** [comment]
@arinzeeze or @caniekwe can you create an openmrs ticket for this just like? https://issues.openmrs.org/browse/RA-1619

**Comment by dkayiwa** [comment]
Corresponding OpenMRS ticket created at https://issues.openmrs.org/browse/RA-1620

**Comment by nsanmi** [comment]
NMRS section completed.
All forms has been conditioned according to programs area and data entry clerks can now access required forms for specific program areas.

**Comment by dkayiwa** [comment]
@nsanmi i think you were meant to comment on another issue. 😊

**Comment by nsanmi** [comment]
@arinzeeze and @caniekwe .
I think this NMRS section is completed.
UI conditions has been implemented based on @arinzeeze  modification to the new coreapp module.
All forms has been conditioned according to programs area and data entry clerks can now access required forms for specific program areas.

**Comment by ahmedsylvanus** [comment]
This has been done, and the code committed to the Dev instance.

**Comment by dkayiwa** [comment]
@ahmedsylvanus am reopening this until when some one posts here a link to the commit.

@arinzeeze did you commit this anywhere that am not yet aware of?

**Comment by arinze1008** [comment]
@dkayiwa I have created the pull request

**Comment by dkayiwa** [comment]
@arinzeeze i have put comments for you on the pull request.

**Comment by multiplechuks** [comment]
@arinzeeze @arinze1008 can you state the steps you used to achieve this

**Comment by arinze1008** [comment]
@dkayiwa, 
The pull request is fine now. All checks have passed.

**Comment by arinze1008** [comment]
@multiplechuks
 https://wiki.openmrs.org/display/docs/Pull+Request+Tips

https://wiki.openmrs.org/display/docs/Using+Git

**Comment by dkayiwa** [comment]
@arinzeeze you have comments to address on the pull request
