### ISSUE TITLE
Data Entry Date Enrolled into ART Program in HIV Enrollement Form is not submitting into the Program Enrollement Table

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#60]
Date Enrolled into Program on the HIV Enrollment Form is not submitting into the patient_program table

**Comment by abrahamolatubosun1973** [comment]
Great Og Bright the Form Entry and Migration team will look into this and provide feed back.
Thanks

**Comment by caniekwe** [comment]
Recheck this again when its all put together.
