### ISSUE TITLE
The Need for a special baseline form to capture status of patient at start of ART

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#61]
There is a need for a seperate form to capture the status of the patient at start of ART. Examples of key variables to be captured in this form include;
Clinical Stage at start of ART
CD4 at Start of ART
Date Initial Adherence Counseling Completed
First Regimen Line at Start of ART
First Regimen at Start of ART
Weight at Start of ART
Height
BMI/MUAC
Functional status at Start
Pregnancy Status at Start of ART
Breastfeeding Status at Start of ART
INH Start Date
INH Stop Date
CTX Start Date
CTX Stop Date
TB Treatment Start Date
TB Treatment Stop Date

**Comment by elameen221** [comment]
**PMTCT Delivery Register** - Complete

**Comment by elameen221** [comment]
A new form called **ART Commencement Form** has been created, it captures all the details listed above.

![ART_C_form](https://user-images.githubusercontent.com/17188731/63702956-ea2efc80-c81f-11e9-84ff-2c7bba341974.png)

The **INH Stop date** concept id is currently not in the concept dictionary, the data migration team would need to include this ID in the dictionary for this field to be activated.

**Comment by elameen221** [comment]
**ART Commencement Form**
The INH **Stop date** concept id `<td><obs conceptId="166096"/></td>`  is currently not in the concept dictionary, the data migration team would need to include this ID in the dictionary for this field to be activated.
