### ISSUE TITLE
Data Entry : Date Sample Collected should be the Encounter Date of all Lab test

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#64]
An Encounter Date is the date a patient had a contact with a service provider. The Label "Visit Date" in Lab Form should be changed to "Date Sample Collected" so that it can become the obs_datetime of the Viral Load and other Lab variables.

**Comment by caniekwe** [comment]
@brightoibe Can we look at what the National tool says and follow that.
