### ISSUE TITLE
Data Entry: The need for Discontinuation/Interruption Form

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#66]
This form is on the front page of the care card and is used by Data Entry clerks to discontinue a patient that has not been coming for a long time. Also can be used by the Doctor to "Stop" a patients ART when there are signs of "Adverse Drug Rection". It contains important data elements like;
Date ART Stoped
Date ART Restarted
Reason for Discontinuation

**Comment by meks285** [comment]
Noted.

To work on this, I will need to have access to the GON Discontinuation form.

**Comment by brightoibe** [comment]
It is at the front page of the Care Card.
Thank you

    On Thursday, August 29, 2019, 11:07:54 AM GMT+1, Ifechelobi Chukwuemeka <notifications@github.com> wrote:  
 
 
Noted.

To work on this, I will need to have access to the GON Discontinuation form.

**Comment by meks285** [comment]
This has been created
