### ISSUE TITLE
NigeriaMRS workflow - Mapping drugs to their regimen 

### ISSUE THREAD

**Issue by iogbonna** [nmrs-nigeria/openmrs-module-nigeriaemr#68]
This issue is for mapping all the drugs to their regimen using the setMember property of the regimen concept

**Comment by caniekwe** [comment]
@Nnalda We need to map the drugs to the regimens so we can implement that in the workflow under the pharmacy form. What we intend to achieve with this:

When the user selects a regimen, we want that only the drugs that make up the regimen combination is populated for the user to provide details as per (dose, strength and frequency). Kindly help us map these regimens attached to the respective drugs that make up the regimen. As you work on this, if you identify any other drugs not listed, please include that. 

We also will need the dosage, strength and frequency for all the listed drugs.
[ARV Regimen List.xlsx](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3545440/ARV.Regimen.List.xlsx)

**Comment by ahmedsylvanus** [comment]
The Mapping is done and will be shared.
