### ISSUE TITLE
Allow prescription and dispensing of adult regimen/formulation for paeds who meet accepted critera

### ISSUE THREAD

**Issue by lisamurie** [nmrs-nigeria/openmrs-module-nigeriaemr#69]
**Problem:**
Sometimes a paediatric patient (age<15 years)  may qualify for  an adult  formulation/regimen  based on his/her weight. 

Improvement:
We need to make prescription and dispensing of adult formulations/Regimen possible for paeds who meet above criteria possible in NMRS.

**Comment by caniekwe** [comment]
Yes. We created the Age category on the pharmacy forms to handle this Instead of filtering the regimens based on patient age
