### ISSUE TITLE
Validation restriction in Hiv Enrollment form 

### ISSUE THREAD

**Issue by opssondesigns** [nmrs-nigeria/openmrs-module-nigeriaemr#77]
Validation restriction in Hiv enrollment form allows Date Confirmed HIV+ to be greater than Date Enrolled in Care.

**Comment by JohnboscoJbTech** [comment]
@opssondesigns this is validated on the live server, please check the version of the database you have...

Check [here](http://41.76.248.129:8080/openmrs/login.htm)
