### ISSUE TITLE
Missing Data Field 

### ISSUE THREAD

**Issue by opssondesigns** [nmrs-nigeria/openmrs-module-nigeriaemr#78]
Date transferred in and ART Start Date missing in Hiv Enrollment form on the live server

**Comment by MrOluGbenga** [comment]
"Date transferred in" and "ART Start Date" are both available on the Hiv Enrollment form, you only need to make the right selection on the switch of the preceding question.

Selecting "Yes" for "Was patient transferred in from another facility" gives you extra fields including "Date transferred in".

Selecting "Yes" for "Was patient previously on ART" gives you extra fields including "ART Start Date".

This issue/ticket should be closed.
