### ISSUE TITLE
Update Adult Clinical Evaluation

### ISSUE THREAD

**Issue by MrOluGbenga** [nmrs-nigeria/openmrs-module-nigeriaemr#80]
Change name to  "Adult Initial Clinical Evaluation"

Concept:	-> Tuberculosis disease status (1659)	
Answers:	

3. TPT(IPT) -> On treatment for disease (1662) (Is Wrongly mapped, should be Isoniazid Preventive Treatment Program - 164128)

Concept:	-> Stop ART (165360) - Change name to "Reason for stop"

Concept:	-> Stop ART (165360) - Change name to "Reason for substitution" and re-map

**Comment by MrOluGbenga** [comment]
Located the right concept ID for TPT(IPT) (164128). Changes will be effected on the live server.

**Comment by caniekwe** [comment]
@MrOluGbenga did you have a discussion with data migration team?
