### ISSUE TITLE
Data Entry : TB Status on Adult Initial Clinical Evaluation Form has a wrongly mapped answer for ON IPT 

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#81]
TB Status on Adult Initial Clinical Evaluation Form is supposed to have 5 options;
1. No signs = no signs or symptoms of TB
2. Presumptive TB = Patient with signs and symptoms of TB and referred for evaluation
3. IPT = Currently on INH prophylaxis
4. Confirmed TB = Patient has active TB                                                                       
5. TB Treatment = Currently on TB treatment

**Comment by MrOluGbenga** [comment]
This has been fixed on my local system. The concept ID (166067) required to fix it on the live server is not available on the live server.

**Comment by MrOluGbenga** [comment]
The changes have been uploaded to the live server.
