### ISSUE TITLE
Working option(an item on functional status) is mapped to a different concept ID on Card Card

### ISSUE THREAD

**Issue by talk2morris** [nmrs-nigeria/openmrs-module-nigeriaemr#82]
The concept ID for item 'Working' is mapped to a different concept ID that is not among the list of coded values for Functional Status.

**Comment by meks285** [comment]
Below are the Members of the obs group:
Physically able to work (**159468**)
Patient ambulatory (**160026**)
Bedridden (**162752**)

Formally the Physically able to Work (Working) member was assigned the ConceptId: **160027**

However, this has now been changed to ConceptId: **159468** and the Form saved successfully.
