### ISSUE TITLE
Next Appointment Date pre-filled with admin (Login details).

### ISSUE THREAD

**Issue by opssondesigns** [nmrs-nigeria/openmrs-module-nigeriaemr#85]
Next Appointment Date for HIV Treatment Follow up form (Care Card) is pre-filled with admin (Login details).

**Comment by talk2morris** [comment]
I thought we agreed that you will handle this

**Comment by MrOluGbenga** [comment]
This issue is browser dependent. It is the browser that decides when to prefill the field, there is no code doing the prefilling. 

However, there is a validation preventing the form from submitting when a date ahead of the encounter date has not been selected. 

This issue should be closed.
