### ISSUE TITLE
Legacy Regimen Migration

### ISSUE THREAD

**Issue by Nnalda** [nmrs-nigeria/openmrs-module-nigeriaemr#86]
I suggest we compile a list of all existing regimens (in all legacy EMRs) across all facilities grouped as “active” and “Inactive” and have them included on NMRS for a successful migration.

**Issue**
Not all legacy regimens are currently listed in NMRS

**Comment by caniekwe** [comment]
@Nnalda thank you for raising this. Can we all extract from our legacy EMR systems the list of all regimens ever documented 
@teggsdgreat can you get us this from SEEDSCare and IQCare
@michaelnnakwe can you get us this from CISPro and FileMakerPro
@brightoibe - can you get us this for IHVN's openmrs
@abrahamolatubosun1973 can you get us this from PWIS.

If we can quickly generate this and share this morning before 10am, then maybe @Nnalda can help us harmonize and share for us to put them into the NMRS. If we can get this done quickly this morning, we can be a bit more hopeful for getting this done in this bootcamp.

**Comment by teggsdgreat** [comment]
Find here list of the various regimen combination for SEEDSCare and IQCare
[seedscare-iqcare_regime.xlsx](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3545959/seedscare-iqcare_regime.xlsx)

**Comment by michaelnnakwe** [comment]
Please attached Regimen combinations from CisPRO and FileMaker PRO

[cispro__filemaker_regimen.xlsx](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3545979/cispro__filemaker_regimen.xlsx)

**Comment by Nnalda** [comment]
> I suggest we compile a list of all existing regimens (in all legacy EMRs) across all facilities grouped as “active” and “Inactive” and have them included on NMRS for a successful migration.
> 
> **Issue**
> Not all legacy regimens are currently listed in NMRS

I hope I have not missed OpenMRS and PWIS lists?

**Comment by brightoibe** [comment]
Am compiling the one for OpenMRS right away. 

Thanks

    On Wednesday, August 28, 2019, 12:21:10 AM GMT+1, Nnalda <notifications@github.com> wrote:  
 
 

I suggest we compile a list of all existing regimens (in all legacy EMRs) across all facilities grouped as “active” and “Inactive” and have them included on NMRS for a successful migration.

Issue
Not all legacy regimens are currently listed in NMRS


I hope I have not missed OpenMRS and PWIS lists?

**Comment by brightoibe** [comment]
Hello Sir,     Find attached OpenMRS drugs and regimen. 

My Proposal1. Let us seperate Regimens and Drugs as different concepts in OpenMRS. 
    Regimens can only exist in 3 or 4 combinations and they are coded. But drugs can exist only in the form dispensed 
    by pharmacist.2. Some of the drugs are already existing in NMRS dictionary. Lets verify before we actually create them
I don't have push access to the files_and_resources so I attached the files here.
Thanks

    On Wednesday, August 28, 2019, 12:21:10 AM GMT+1, Nnalda <notifications@github.com> wrote:  
 
 

I suggest we compile a list of all existing regimens (in all legacy EMRs) across all facilities grouped as “active” and “Inactive” and have them included on NMRS for a successful migration.

Issue
Not all legacy regimens are currently listed in NMRS


I hope I have not missed OpenMRS and PWIS lists?

**Comment by Nnalda** [comment]
I am working towards sending the harmonized list of ART regimens and the corresponding formulations tonight.

**Comment by Nnalda** [comment]
Dear Colleagues,
The harmonized list of regimens and corresponding drug formulations is attached.
 
[Harmonized_ART_Regimen_List_NMRS_v1.xlsx](https://github.com/nmrs-nigeria/openmrs-module-nigeriaemr/files/3566664/Harmonized_ART_Regimen_List_NMRS_v1.xlsx)

**Comment by ahmedsylvanus** [comment]
All Legacy regimens have been added to NMRS and their associated drug combinations mapped.
