### ISSUE TITLE
Some Codetypes Mapping missing on NDR xsd

### ISSUE THREAD

**Issue by talk2morris** [nmrs-nigeria/openmrs-module-nigeriaemr#87]
I noticed that some codetypes mapping are missing on the current NDR xsd version 1.3...so going forward any related items should come in here as a comment on this issue.

**Comment by talk2morris** [comment]
I noticed that some codetypes mapping are missing on the current NDR xsd version 1.3...so going forward any related items should come in as here as a comment on this issue.

**Comment by talk2morris** [comment]
Also on the xsd, the codetypes for NotedSideEffects is missing, while the NDR Dictionary the codetypes are as follows:

1 | Nausea/vomiting
-- | --
2 | Headache
3 | Insomnia/bad   dreams
4 | Fatigue/weakness
5 | PV   bleeding/discharge
6 | Rash
7 | FAT changes
8 | Anemia
9 | Drainage of   liquid
10 | Stevens   Johnson syndrome
11 | Hyperglycemia

**Comment by caniekwe** [comment]
@wonderfulguru1 you can work on 

- DurationOnArt
- PatientFamilyPlanningMethodCode
- FunctionalStatus

@emadubuko can work on these
- OtherOIOtherProblems
- WhyPoorFairARVDrugAdherence
- CD4
- CD4TestDate

**Comment by talk2morris** [comment]
@caniekwe we discussed, the agreed way to captured these is to use comma separation for each item
