### ISSUE TITLE
ART Commencement Form: Missing Concept ID in the Dictionary

### ISSUE THREAD

**Issue by elameen221** [nmrs-nigeria/openmrs-module-nigeriaemr#90]
**ART Commencement Form** (newly created)
The INH **_Stop date_** concept id `<td><obs conceptId="166096"/></td>` is currently not in the concept dictionary, the data migration team would need to include this ID in the dictionary for this field to be activated.

 @elameen221

**Comment by lisamurie** [comment]
@abrahamolatubosun1973 @teggsdgreat could you please follow up on this. Is "ART Commencement Form" a new form? or same as Adult/Paediatric Initial Evaluation forms?

**Comment by ahmedsylvanus** [comment]
@abrahamolatubosun1973  @teggsdgreat @michaelnnakwe  any update on this

**Comment by teggsdgreat** [comment]
This is resolved, the concept is present in NMRS but not in the global concept dictionary

**Comment by lisamurie** [comment]
@teggsdgreat how has this been resolved?

**Comment by teggsdgreat** [comment]
@lisamurie  We are putting together all the new concepts for follow up in adding them to the global dictionary
