### ISSUE TITLE
Creating a new JSON reporting App with a fat tab button on the homepage for all program area reports

### ISSUE THREAD

**Issue by gibrilg** [nmrs-nigeria/openmrs-module-nigeriaemr#95]
This is different from the previous reporting interface, this new app allows users to manage report via the Reference Application UI and likewise give you the option of choosing whether to preserve generated reports for future use.

**Comment by lisamurie** [comment]
@gibrilg could you please provide link to relevant resources?

**Comment by gibrilg** [comment]
Check this out: https://wiki.openmrs.org/display/docs/System+Administration%3A+Manage+Apps
