### ISSUE TITLE
ARV Drugs Adherence Concept Answers on the Care Card are wrongly mapped

### ISSUE THREAD

**Issue by brightoibe** [nmrs-nigeria/openmrs-module-nigeriaemr#96]
Fair was mapped to Poor 
and 
Poor was mapped to Fair
Also it will be nice to arrange the drop down the same way it was arranged on the paper form e.g Good,Fair,Poor  and not Fair, Good, Poor

**Comment by meks285** [comment]
Noted

**Comment by meks285** [comment]
This has been resolved.

Recommended for Closure.
